### ISSUE TITLE
can't search on hyphens

### ISSUE THREAD

**Issue by mjpost** [mjpost/bibsearch#21]
Searching for hyphenated names causes an error:

```bash
$ bibsearch search callison-burch
Traceback (most recent call last):
  File "/Users/mattpost/code/bibsearch/bibsearch.py", line 723, in <module>
    main()
  File "/Users/mattpost/code/bibsearch/bibsearch.py", line 720, in main
    args.func(args)
  File "/Users/mattpost/code/bibsearch/bibsearch.py", line 381, in _find
    format_search_results(db.search(args.terms), args.bibtex, args.original_key)
  File "/Users/mattpost/code/bibsearch/bibsearch.py", line 178, in search
    [" ".join(query)])
sqlite3.OperationalError: no such column: burch
```

**Comment by davvil** [comment]
That's a feature, not a bug. :-D The '-' is used by FTS to exclude columns in the search.

Short term solution: quote your query: `bibsearch search '"callison-burch"'`

I am planing on sanitizing (i.e. automatically quoting) the queries at the same time I do the macro implementation of #13.

**Comment by davvil** [comment]
Should be solved in current master. Reopen if you find other issues.
