### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by kirk86** [mjpost/bibsearch#47]
I just installed and got the following error:
```
bibsearch add bib://list
acl       The ACL Anthology [https://aclanthology.coli.uni-
          saarland.de/]
nips      The NIPS conference [https://nips.cc/]
pmlr      Proceedings of machine learning research (includes ICML)
          [http://proceedings.mlr.press/]
Traceback (most recent call last):
  File "/Users/user/miniconda3/bin/bibsearch", line 10, in <module>
    sys.exit(main())
  File "/Users/user/miniconda3/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 758, in main
    args.func(args, config)
  File "/Users/user/miniconda3/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 481, in _add
    else get_fnames_from_bibset(raw_fname, config.database_url)
  File "/Users/user/miniconda3/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 345, in get_fnames_from_bibset
    name, description = line.split("\t")
ValueError: not enough values to unpack (expected 2, got 1)
```
It seems like `line.split("\t")` returns one value instead of two

**Comment by mjpost** [comment]
Ah, these are out of date with the new Anthology.

Instead of using the shortcuts, you can install ACL direct from its complete BibTeX:

```bash
wget -O- https://aclweb.org/anthology/anthology.bib.gz | gzip -cd > acl-anthology.bib
bibsearch add acl-anthology.bib
```

We'll fix these pieces.
