### ISSUE TITLE
error when executing list available anthologies

### ISSUE THREAD

**Issue by kirk86** [mjpost/bibsearch#49]
As per the instructions I execute
`bibsearch add bib://list`

and getting the following error
```
acl       The ACL Anthology [https://aclanthology.coli.uni-
          saarland.de/]
nips      The NIPS conference [https://nips.cc/]
pmlr      Proceedings of machine learning research (includes ICML)
          [http://proceedings.mlr.press/]
Traceback (most recent call last):
  File "/home/user/papis/bin/bibsearch", line 10, in <module>
    sys.exit(main())
  File "/home/user/papis/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 758, in main
    args.func(args, config)
  File "/home/user/papis/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 481, in _add
    else get_fnames_from_bibset(raw_fname, config.database_url)
  File "/home/user/papis/lib/python3.7/site-packages/bibsearch/bibsearch.py", line 345, in get_fnames_from_bibset
    name, description = line.split("\t")
ValueError: not enough values to unpack (expected 2, got 1)

```

**Comment by kirk86** [comment]
Additionally,
is it possible to use `bibsearch` in order to automatically fix a local bib file. For instance, going through each entry in the local .bib file and when finding that there are missing required entries filling them up correctly by finding the corresponding entry in one of the downloaded anthologies and completing the missing entries with the correct corresponding info?

**Comment by mjpost** [comment]
Hi! Thanks for the comment. I'm afraid this has fallen into a bit of disrepair. The Anthology source, for example, is now properly at `http://www.aclweb.org/anthology` and should be downloaded from there.

I don't have time at the moment to look into this but maybe @davvil does...
